# RBS type definitions for Emf2svg::Records::Path
module Emf2svg
  module Records
    class Path < Base
      def process: (Hash[Symbol, untyped] record) -> void

      private

      def process_beginpath: (Hash[Symbol, untyped] record) -> void
      def process_endpath: (Hash[Symbol, untyped] record) -> void
      def process_closefigure: (Hash[Symbol, untyped] record) -> void
      def process_fillpath: (Hash[Symbol, untyped] record) -> void
      def process_strokepath: (Hash[Symbol, untyped] record) -> void
      def process_strokeandfillpath: (Hash[Symbol, untyped] record) -> void
    end
  end
end
